#!/usr/bin/env bash
# PreToolUse(Edit|Write|NotebookEdit): refuse writes to files that must be produced
# by tooling rather than typed by hand.
#
# Hand-editing a lockfile is the specific failure this exists to stop: it produces a
# file that looks right, installs differently on CI, and costs an afternoon to find.
# Same for generated code — the edit survives until the next regeneration, then
# vanishes silently.
#
# Escape hatch: TOKENSAVER_ALLOW_HAZARD=1
set -uo pipefail

[[ "${TOKENSAVER_ALLOW_HAZARD:-0}" == "1" ]] && exit 0
command -v jq >/dev/null 2>&1 || exit 0

input=$(cat)
path=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' <<<"$input" 2>/dev/null) || exit 0
[[ -z "$path" ]] && exit 0

deny() {
  jq -n --arg r "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $r
    }
  }'
  exit 0
}

base=$(basename "$path")
tree=""

# --- Lockfiles -------------------------------------------------------------
case "$base" in
  package-lock.json|pnpm-lock.yaml|yarn.lock|bun.lockb|poetry.lock|Pipfile.lock|Cargo.lock|composer.lock|go.sum|uv.lock)
    deny "Refusing to hand-edit '$base'. A hand-edited lockfile resolves differently on CI than it does here, and the mismatch is expensive to diagnose.

Use the package manager instead — for example 'npm install <pkg>', 'pnpm add <pkg>', 'poetry lock', or 'cargo update'. Then commit the lockfile it produces.
Override with TOKENSAVER_ALLOW_HAZARD=1." ;;
esac

# --- Vendored / installed trees -------------------------------------------
case "$path" in
  */node_modules/*|*/.venv/*|*/venv/*|*/site-packages/*|*/vendor/*|*/.git/*)
    for d in node_modules .venv venv site-packages vendor .git; do
      [[ "$path" == */"$d"/* ]] && tree="$d" && break
    done
    deny "Refusing to write inside '${tree}'. Changes there are overwritten on the next install and are never committed.

Change the source, or if you must patch a dependency use the project's patch tooling (e.g. patch-package).
Override with TOKENSAVER_ALLOW_HAZARD=1." ;;
esac

# --- Files that declare themselves generated -------------------------------
if [[ -f "$path" ]]; then
  if head -5 "$path" 2>/dev/null | grep -qiE '(@generated|DO NOT EDIT|AUTO-GENERATED|Code generated by)'; then
    marker=$(head -5 "$path" | grep -iEm1 '(@generated|DO NOT EDIT|AUTO-GENERATED|Code generated by)' | sed 's/^[[:space:]]*//' | cut -c1-70)
    deny "Refusing to edit '$base' — it declares itself generated:
  $marker

Edit the source it is generated from and re-run the generator, or your change disappears at the next regeneration.
Override with TOKENSAVER_ALLOW_HAZARD=1."
  fi
fi

exit 0
